// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id int64) error
	GetTodo(ctx context.Context, id int64) (Todo, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
